### ISSUE TITLE
Glossary with travel terms

### ISSUE THREAD

**Issue by tsolakoua** [amadeus4dev/developer-guides#109]
- Fare: the price of a ticket for a particular flight or travel itinerary
- Booking: the process of reserving a seat on a flight or a room in a hotel
- Ticketing: The process of issuing a travel document, typically a paper or electronic ticket, that confirms that a passenger has purchased a seat on a flight, train, bus, or other form of transportation.
- Baggage allowance: the amount of luggage that a passenger is allowed to carry on a flight without additional charges
- Additional Baggage: Luggage beyond the standard allowance provided by an airline, subject to additional fees.
- Fare Rules: The terms and conditions that apply to a specific airline ticket or fare, including restrictions and information on refunds, cancellations, changes, baggage, seat assignments, upgrades, and frequent flyer programs.
- Direct flight: a flight that goes from one destination to another without any stops in between
- Layover: a stopover in a destination en route to the final destination
- Non-stop flight: a flight that goes from one destination to another without any stops in between
- Round-trip: a trip that includes travel to a destination and then back to the original departure point
- Multi-stop flight: a flight itinerary that includes stops at multiple destinations before reaching the final destination
- GDS (Global Distribution System): a computerized system used by travel agents and airlines to search for and book flights, hotels, rental cars, and other travel-related services
- PNR (Passenger Name Record): a record in a computer reservation system that contains the details of a passenger's itinerary and contact information
- Airline consolidators: are wholesalers of air tickets that usually partner with airlines to get negotiated rates for air tickets, and then resell the air tickets to travel agents or consumers.
- Cabin: The section of an aircraft or train where passengers sit during their trip. It is divided into different classes, such as first class, business class, and economy class, each one with different amenities and prices.
- Seatmap: A map or diagram of the seating layout in the cabin of an aircraft or train. It shows the location of different types of seats, such as exit row, bulkhead seat, aisle seat, window seat. It can be used to choose a seat or to see the availability of seats for a certain flight.
- Ticketing: The process of issuing a travel document, typically a paper or electronic ticket, that confirms that a passenger has purchased a seat on a flight, train, bus, or other form of transportation. It can be refundable or non-refundable, one-way or round-trip, and open-jaw.
- Amenities: Additional services or features offered to enhance the experience of the passengers, such as food, entertainment, Wi-Fi, extra legroom, baggage allowance, frequent flyer programs, and lounge access. They can vary depending on the class of service and the airline/train company.
- Travel Classes: Differentiation of service level and amenities offered to passengers on an aircraft or train, like first class, business class, economy class.
- Commission: Fee paid to intermediaries for booking travel-related services, usually a percentage of the total cost.
- Amadeus Office ID: An identification number assigned to travel agencies to access Amadeus system and book reservations.
- Pricing: The process of determining the cost of a product or service, in the context of travel it refers to the cost of airline tickets, hotel rooms, rental cars, etc. which can change frequently based on demand and other factors.

**Comment by minjikarin** [comment]
PNR : we can include a link for this blog post https://developers.amadeus.com/blog/what-is-pnr-booking-reference
