### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by DaDudeIan** [amadeus4dev/developer-guides#163]
Hello. I'm using POI API to create an app, and everything worked fine yesterday. Today I'm not able to make API calls anywhere seemingly. I've tried using the curl command in a terminal, the API Explorer from the Docs page, and launching the app on a physical phone and an emulator. I just get the error mentioned in the title. Is there somewhere it's possible to view the status of the APIs, and whether they're up or not? Thanks.

**Comment by tsolakoua** [comment]
We suggest you to get in touch with the [support team](https://developers.amadeus.com/support) for any issues you might have noticed for specific APIs. Also, as of today there is no status page available.
