### ISSUE TITLE
I keep getting 500 Proxy Error Response

### ISSUE THREAD

**Issue by REA0413** [amadeus4dev/developer-guides#254]
Dear Amadeus Team,

This is the link I tried to visit
https://developers.amadeus.com/self-service/apis-docs/guides/developer-guides/

I tried to change web browsers, used VPN, but still got this response.
"Proxy Error

The proxy server could not handle the request
Reason: Error during SSL Handshake with remote server"

<img width="1440" alt="Screenshot 2024-12-09 at 18 09 14" src="https://github.com/user-attachments/assets/14ac571a-8ac5-486d-bac5-6d299bec3d16">

Hopefully this can be resolved soon as I'm interested on implementing Amadeus' API in my web app.

Thanks.

**Comment by tsolakoua** [comment]
@REA0413 The team is working on fixing the issue. For the time being you can check the markdown files directly on the repository, or clone it and run it locally. In the contributor's guide you can find the instructions.

**Comment by tsolakoua** [comment]
The guides now work, closing the issue.
