### ISSUE TITLE
3 APIs missing from test data collections

### ISSUE THREAD

**Issue by minjikarin** [amadeus4dev/developer-guides#68]
https://github.com/amadeus4dev/developer-guides/blob/313ed1a2e65066bb211722660d11bc21c0f9b24f/docs/test-data.md?plain=1#L1

3 APIs missing : 
- Airline Routes
- Hotel List
- City Search

**Comment by tsolakoua** [comment]
I also think that Flight Inspiration Search and Flight Cheapest Data data collection is not accurate anymore. Since we have a cache the is refreshed.
