### ISSUE TITLE
/shopping/flight-offers/pricing is returning http 500

### ISSUE THREAD

**Issue by kazimanzurrashid** [amadeus4dev/developer-guides#8]
I am posting the following payload:

`{
  "data": {
    "type": "flight-offers-pricing",
    "flightOffers": [
      {
        "id": "1",
        "type": "flight-offer",
        "source": "GDS",
        "instantTicketingRequired": false,
        "nonHomogeneous": false,
        "oneWay": false,
        "lastTicketingDate": "2020-05-27T00:00:00",
        "numberOfBookableSeats": 2,
        "itineraries": [
          {
            "duration": "PT17H5M",
            "segments": [
              {
                "id": "6",
                "number": "6",
                "departure": {
                  "iataCode": "LHR",
                  "terminal": "4",
                  "at": "2020-05-27T22:05:00"
                },
                "arrival": {
                  "iataCode": "BAH",
                  "at": "2020-05-28T06:50:00"
                },
                "operating": {
                  "carrierCode": "GF"
                },
                "aircraft": {
                  "code": "789"
                },
                "duration": "PT6H45M",
                "carrierCode": "GF",
                "numberOfStops": 0,
                "blacklistedInEU": false
              },
              {
                "id": "7",
                "number": "508",
                "departure": {
                  "iataCode": "BAH",
                  "at": "2020-05-28T15:45:00"
                },
                "arrival": {
                  "iataCode": "DXB",
                  "terminal": "1",
                  "at": "2020-05-28T18:10:00"
                },
                "operating": {
                  "carrierCode": "GF"
                },
                "aircraft": {
                  "code": "320"
                },
                "duration": "PT1H25M",
                "carrierCode": "GF",
                "numberOfStops": 0,
                "blacklistedInEU": false
              }
            ]
          },
          {
            "duration": "PT10H20M",
            "segments": [
              {
                "id": "16",
                "number": "501",
                "departure": {
                  "iataCode": "DXB",
                  "terminal": "1",
                  "at": "2020-05-30T08:00:00"
                },
                "arrival": {
                  "iataCode": "BAH",
                  "at": "2020-05-30T08:15:00"
                },
                "operating": {
                  "carrierCode": "GF"
                },
                "aircraft": {
                  "code": "320"
                },
                "duration": "PT1H15M",
                "carrierCode": "GF",
                "numberOfStops": 0,
                "blacklistedInEU": false
              },
              {
                "id": "17",
                "number": "3",
                "departure": {
                  "iataCode": "BAH",
                  "at": "2020-05-30T10:05:00"
                },
                "arrival": {
                  "iataCode": "LHR",
                  "terminal": "4",
                  "at": "2020-05-30T15:20:00"
                },
                "operating": {
                  "carrierCode": "GF"
                },
                "aircraft": {
                  "code": "789"
                },
                "duration": "PT7H15M",
                "carrierCode": "GF",
                "numberOfStops": 0,
                "blacklistedInEU": false
              }
            ]
          }
        ],
        "price": {
          "currency": "EUR",
          "total": "822.66",
          "base": "204.00",
          "fees": [
            {
              "type": "SUPPLIER",
              "amount": "0.00"
            },
            {
              "type": "TICKETING",
              "amount": "0.00"
            }
          ],
          "grandTotal": "822.66"
        },
        "pricingOptions": {
          "fareType": [
            "PUBLISHED"
          ],
          "includedCheckedBagsOnly": true
        },
        "validatingAirlineCodes": [
          "GF"
        ],
        "travelerPricings": [
          {
            "travelerId": "1",
            "fareOption": "STANDARD",
            "travelerType": "ADULT",
            "price": {
              "currency": "EUR",
              "total": "411.33",
              "base": "102.00"
            },
            "fareDetailsBySegment": [
              {
                "segmentId": "6",
                "cabin": "ECONOMY",
                "fareBasis": "W9WUK4A",
                "class": "W",
                "includedCheckedBags": {
                  "quantity": 1
                }
              },
              {
                "segmentId": "7",
                "cabin": "ECONOMY",
                "fareBasis": "W9WUK4A",
                "class": "W",
                "includedCheckedBags": {
                  "quantity": 1
                }
              },
              {
                "segmentId": "16",
                "cabin": "ECONOMY",
                "fareBasis": "S9WUK4A",
                "class": "S",
                "includedCheckedBags": {
                  "quantity": 1
                }
              },
              {
                "segmentId": "17",
                "cabin": "ECONOMY",
                "fareBasis": "S9WUK4A",
                "class": "S",
                "includedCheckedBags": {
                  "quantity": 1
                }
              }
            ]
          },
          {
            "travelerId": "2",
            "fareOption": "STANDARD",
            "travelerType": "ADULT",
            "price": {
              "currency": "EUR",
              "total": "411.33",
              "base": "102.00"
            },
            "fareDetailsBySegment": [
              {
                "segmentId": "6",
                "cabin": "ECONOMY",
                "fareBasis": "W9WUK4A",
                "class": "W",
                "includedCheckedBags": {
                  "quantity": 1
                }
              },
              {
                "segmentId": "7",
                "cabin": "ECONOMY",
                "fareBasis": "W9WUK4A",
                "class": "W",
                "includedCheckedBags": {
                  "quantity": 1
                }
              },
              {
                "segmentId": "16",
                "cabin": "ECONOMY",
                "fareBasis": "S9WUK4A",
                "class": "S",
                "includedCheckedBags": {
                  "quantity": 1
                }
              },
              {
                "segmentId": "17",
                "cabin": "ECONOMY",
                "fareBasis": "S9WUK4A",
                "class": "S",
                "includedCheckedBags": {
                  "quantity": 1
                }
              }
            ]
          }
        ]
      }
    ]
  }
}`

And it is returning:

`{
  "errors": [
    {
      "code": "38189",
      "title": "Internal error",
      "detail": "An internal error occurred, please contact your administrator",
      "status": "500"
    }
  ]
}`

**Comment by anthonyroux** [comment]
Hi,

I just tried your body message and it works fine. Do you use the right path:

> https://test.api.amadeus.com/v1/shopping/flight-offers/pricing

Note: It is v1 not /v2/

**Comment by kazimanzurrashid** [comment]
Is not it under /v2 ?

**Comment by anthonyroux** [comment]
The Flight Offers Search yes, not the [Flight Offers Price](https://developers.amadeus.com/self-service/category/air/api-doc/flight-offers-price/api-reference)

![image](https://user-images.githubusercontent.com/713173/82454585-373fb680-9ab2-11ea-84d8-e087f8df8ffb.png)

**Comment by kazimanzurrashid** [comment]
Ok got it.
